project:
  type: website
  output-dir: docs

website:
  favicon: "favicon.jpeg"
  site-url: https://sagrikachugh.github.io/
  navbar:
    right:
      - href: index.qmd
        text: Home
      - research.qmd
      - outreach.qmd
      - publications.qmd
  page-footer: 
    background: light
    left: 
     - "Copyright 2024, Sagrika Chugh"
format:
  html:
    theme: 
       - styles.scss
    toc: true
    page-layout: full

editor: visual

