project:
  type: website
  output-dir: docs

website:
  title: Sagrika Chugh
  favicon: "images/favicon.jpeg"
  site-url: https://sagrikachugh.github.io/
  navbar:
    logo:  "images/favicon.jpeg"
    right: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - text: "Research"  
        file: research.qmd
      - text: "Experience" 
        file: experience.qmd
      - text: "Outreach"
        file: outreach.qmd
      - text: "Publications"  
        file: publications.qmd
  page-footer: 
    background: light
    left: 
     - "Copyright 2024, Sagrika Chugh"
format:
  html:
    theme: 
       - styles.scss
    toc: true
    page-layout: full

editor: visual

